[build]
  base = "server"
  publish = "public"
  command = "npm install"

[functions]
  directory = "functions"
  included_files = ["data/**"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build.environment]
  NODE_VERSION = "18" 