[build]
  base = "server"
  publish = "public"
  command = "npm install"

[functions]
  directory = "functions"
  included_files = ["data/**", "../data/**"]

[[redirects]]
  from = "/api/chat/*"
  to = "/.netlify/functions/chat:splat"
  status = 200

[[redirects]]
  from = "/api/resume/save"
  to = "/.netlify/functions/resume-save"
  status = 200

[[redirects]]
  from = "/api/resume"
  to = "/.netlify/functions/resume"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build.environment]
  NODE_VERSION = "18" 